### PR TITLE
Added the NaNO3-KNO3-Medium properites to TRANSFORM.

### PR DESCRIPTION
**Pull request by nelsonsw5wn**
[Molten salts database for energy applications-1307.7343.pdf](https://github.com/ORNL-Modelica/TRANSFORM-Library/files/4880440/Molten.salts.database.for.energy.applications-1307.7343.pdf)
Reference for this change is taken from:
Molten salts database for energy applicatons
R. Sorrano-Lopez, J. Fradera, S. Cuesta-Lopez

### CODE REVIEW

**Comment by greenwoodms06** [comment]
I don't see a test for the media, go ahead and duplicate a similar test in the examples and verify this media works as expected, may have to adjust `beta_const`.

**Comment by greenwoodms06** [comment]
2 things I noticed.
1. It appears the media package you added was saved as a single file rather than a directory structure. To change that right click on `Attributes`. Then make sure `Store as one file` is not selected.
2. there should be a change to the file `package.order` as well where it added the file names. This file tells the IDE to load the file. Without it the media does not appear.

Try to correct these two things.

**Comment by nelsonsw5wn** [comment]
Ok done.

**Comment by greenwoodms06** [comment]
It looks like Therminol_66 was accidentally removed from the `package.order` file.

**Comment by nelsonsw5wn** [comment]
Probably not because I'm working from a version pulled months ago.  Im
betting you added this recently i.e. the last few months

I'll update the repo and redo things but a merge should pick up on the
differences in the branches and maintain the Therminol_66.

--Scott

**Comment by greenwoodms06** [comment]
Yes it is critical to always pull the master branch before being allowed to merge a pull request so that all other changes/contributions to not get erased.

**Comment by greenwoodms06** [comment]
Is this pull request still active? I believe it is waiting for actions from you.

**Comment by nelsonsw5wn** [comment]
I need to grab the latest from the repo and then import my changes again
then submit it again.

**Pull request closed without merging**
